### ISSUE TITLE
Replace use of ByteBuf's 'hasArray()' method

### ISSUE THREAD

**Issue by aldemirenes** [snowplow/JavaNSQClient#1]
Normally, hasArray() method of the Netty ByteBuf class should return true when there is a underlying byte array in the ByteBuf object and this byte array can be directly used when hasArray() returned true. But, hasArray() behaves unexpectedly when another library uses Netty too. I reached this conclusion because I observe this behaviour only with Snowplow Elasticsearch Loader's TCP version which uses [elastic4s](https://github.com/sksamuel/elastic4s) which uses netty. This can be related with incompatibility between the different versions of the netty but instead of the diving in the netty, it will be better to make changes in this project and removing the parts with 'hasArray()' method.

**Comment by alexanderdean** [comment]
Please update commit per ticket title
