### ISSUE TITLE
Use SBT as a build tool

### ISSUE THREAD

**Issue by aldemirenes** [snowplow/JavaNSQClient#3]

**Comment by BenFradet** [comment]
This makes it highly unlikely that this fork will be merged back to the original repo in the future.

**Comment by aldemirenes** [comment]
After we talked with Anton, we decided that using SBT will be better while adding CI/CD to project. Also, I think that not merging this project to the original one will be better because there is not much support right now in the original one.

**Comment by alexanderdean** [comment]
We typically use Gradle for Java projects, but SBT is okay too.
